"""Measure the Week 4 dense baseline against BM25 + RRF retrieval."""

from __future__ import annotations

import json
import statistics
import time

from rag_app.config import load_settings
from rag_app.rag import GeminiRAG


def main() -> None:
    settings = load_settings()
    golden_set_path = settings.project_root / "questions" / "week4_golden.json"
    report_path = settings.project_root / "week4_results.md"
    golden_set = json.loads(golden_set_path.read_text(encoding="utf-8"))

    rag = GeminiRAG(settings.api_key, settings.index_path, settings.llm_model)
    rag.index_documents(settings.documents_dir)
    baseline = [measure(rag, item, "dense") for item in golden_set]
    hybrid = [measure(rag, item, "hybrid") for item in golden_set]

    for item, record in zip(golden_set, baseline):
        answer, _ = rag.answer_from_sources(item["question"], record["sources"])
        record["answer"] = answer
        record["failure"] = classify_failure(item, record)

    report_path.write_text(build_report(golden_set, baseline, hybrid), encoding="utf-8")
    print(f"Week 4 report written to {report_path.name}")


def measure(rag: GeminiRAG, item: dict, strategy: str) -> dict:
    started = time.perf_counter()
    sources = rag.retrieve(item["question"], top_k=3, strategy=strategy)
    latency_ms = (time.perf_counter() - started) * 1000
    rank = next(
        (index for index, source in enumerate(sources, start=1)
         if source.chunk.id == item["expected_chunk_id"]),
        None,
    )
    return {"sources": sources, "rank": rank, "latency_ms": latency_ms}


def classify_failure(item: dict, record: dict) -> str:
    if record["rank"] is None:
        return "R"
    return "G" if normalise(item["expected_fact"]) not in normalise(record["answer"]) else "PASS"


def build_report(golden_set: list[dict], baseline: list[dict], hybrid: list[dict]) -> str:
    baseline_hits = sum(record["rank"] is not None for record in baseline)
    hybrid_hits = sum(record["rank"] is not None for record in hybrid)
    baseline_p50 = statistics.median(record["latency_ms"] for record in baseline)
    hybrid_p50 = statistics.median(record["latency_ms"] for record in hybrid)
    r_count = sum(record["failure"] == "R" for record in baseline)
    g_count = sum(record["failure"] == "G" for record in baseline)
    golden_rows = "\n".join(
        f"| {item['id']} | {item['question']} | {item['expected_chunk_id']} | {item['expected_fact']} |"
        for item in golden_set
    )
    result_rows = "\n".join(
        result_row(item, before, after)
        for item, before, after in zip(golden_set, baseline, hybrid)
    )
    failure_rows = "\n".join(
        failure_evidence(item, record)
        for item, record in zip(golden_set, baseline)
        if record["failure"] != "PASS"
    ) or "No baseline failures."

    shipping_decision = (
        f"Ship BM25 + RRF: it improved or maintained hit-rate@3 at {hybrid_hits}/12 "
        f"with p50 retrieval latency of {hybrid_p50:.1f} ms."
        if hybrid_hits >= baseline_hits
        else f"Do not ship BM25 + RRF yet: it lowered hit-rate@3 from {baseline_hits}/12 to {hybrid_hits}/12."
    )
    return f"""# Week 4 Retrieval Evaluation

Generated by `python evaluate_week4.py`. Regenerate after changing documents or retrieval code.

## Golden set

| ID | Question | Known-correct chunk | Expected fact |
|---|---|---|---|
{golden_rows}

At least four questions contain exact tokens, quantities, or temperatures: W4-01, W4-03, W4-04, W4-08, W4-10, and W4-12.

## One retrieval change

Baseline inspection found **R={r_count}** retrieval failures and **G={g_count}** generation failures. The golden set contains exact ingredient names, quantities, and temperatures, so the one chosen retrieval change is **BM25 + Reciprocal Rank Fusion (RRF, k=60)**. No reranker or embedding-model change was made. RRF fuses rank positions instead of adding incomparable cosine and BM25 raw scores; it should target R failures, not G failures.

## Before and after

| Metric | Dense baseline | BM25 + RRF |
|---|---:|---:|
| Hit-rate@3 | {baseline_hits}/12 ({baseline_hits / 12:.1%}) | {hybrid_hits}/12 ({hybrid_hits / 12:.1%}) |
| p50 retrieval latency/query | {baseline_p50:.1f} ms | {hybrid_p50:.1f} ms |

## Failure inspection (baseline)

Tally: **R={r_count}, G={g_count}, Not-In-Corpus=0**. Every golden-set question is answerable from the indexed recipe cards. `R` means the known chunk was absent from top-3; `G` means it was present but the answer missed the expected fact. Manually confirm any G result before submitting because valid Gemini wording can differ.

{failure_rows}

## Per-question outcome

| ID | Dense rank | Hybrid rank | Status | Dense latency |
|---|---:|---:|---|---:|
{result_rows}

## What the change fixed

Rows marked **fixed** are original R-failures that BM25 + RRF moved into top-3. **Still broken** rows remained retrieval failures. **Not touched (G)** identifies an answer-generation failure that a retrieval-only change should not be expected to fix.

## Shipping decision

{shipping_decision}
"""


def result_row(item: dict, before: dict, after: dict) -> str:
    if before["rank"] is None and after["rank"] is not None:
        status = "fixed"
    elif before["rank"] is None:
        status = "still broken"
    elif before["failure"] == "G":
        status = "not touched (G)"
    else:
        status = "already passed"
    return (
        f"| {item['id']} | {before['rank'] or 'MISS'} | {after['rank'] or 'MISS'} | "
        f"{status} | {before['latency_ms']:.1f} ms |"
    )


def failure_evidence(item: dict, record: dict) -> str:
    retrieved = ", ".join(source.chunk.id for source in record["sources"])
    if record["failure"] == "R":
        return f"- **{item['id']} — R:** expected `{item['expected_chunk_id']}` is absent from top-3 (`{retrieved}`)."
    return (
        f"- **{item['id']} — G:** expected chunk `{item['expected_chunk_id']}` is in top-3, "
        f"but baseline answer was: {record['answer']}"
    )


def normalise(value: str) -> str:
    return " ".join(value.lower().split())


if __name__ == "__main__":
    main()
